### ISSUE TITLE
jirabix action not work Zabbix 4.2

### ISSUE THREAD

**Issue by piterjakubowski** [OSidorenkov/zabbix-jira#13]
Hello, 
does this script work with zabbix 4.2 ?

I copied the script and created media types and actions (Administration -> Create Action  (Event source Internal )) according to readme. 
I will add that when it performs the test the ticket is created.

Regards, 
Piotr

**Comment by DenissStepanov** [comment]
Hi,

please specify what exactly wrong. what kind of error or screenshot

**Comment by piterjakubowski** [comment]
I fixed my problem

**Comment by DenissStepanov** [comment]
Maybe you can help me in that case. On 4.4.1when triggers go to done/acknowlegde state they generate a new ticket for that, on problem discription I got
`Traceback (most recent call last):
File "/var/lib/zabbixsrv/alertscripts/jirabix.py", line 230, in <module>
main()
File "/var/lib/zabbixsrv/alertscripts/jirabix.py", line 210, in main
settings["zbx_image_height"], tmp_dir)
File "/var/lib/zabbixsrv/alertscripts/jirabix.py", line 88, in graph_get
title = requests.utils.quote(title)
File "/usr/lib64/python2.7/urllib.py", line 1270, in quote
raise TypeError('None object cannot be quoted')
TypeError: None object cannot be quoted`

And no info on problem ticket comes only generate that. Do you have the same problem?
